# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestSearch1():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        # 隐式等待5秒钟
        # self.driver.implicitly_wait(5)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_search1(self):
        # Test name: search1
        # Step # | name | target | value | comment
        # 1 | open | / |  |
        self.driver.get("https://ceshiren.com/")
        # 2 | setWindowSize | 1057x814 |  |
        # 注意可以在浏览器的console控制台输入$("#search-button[title=搜索]")进行测试，看是否能找到元素
        self.driver.find_element(By.CSS_SELECTOR, "#search-button[title=搜索]").click()
        self.driver.find_element(By.CSS_SELECTOR, ".show-advanced-search").click()
        self.driver.find_element(By.CSS_SELECTOR, "input.search-query").click()
        self.driver.find_element(By.CSS_SELECTOR, "input.search-query").send_keys("selenium")
        # 或者self.driver.find_element(By.CSS_SELECTOR, ".search bar .search-cta").click()，父子级关系
        # 输入selenium点击搜索按钮
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary.search-cta").click()
        # 点击搜索结果的第一条信息
        """
            由于还没有查询结果返回，所以没有如下class内容，所以点击具体的某一条信息的时候报错，
            no such element: Unable to locate element，在这里需要隐式等待或显示等待，等待查询结果出来后记性查看具体每一条的详情
        """
        # self.driver.find_element(By.CSS_SELECTOR, ".topic-title").click()
        self.driver.implicitly_wait(5)
        print("接口返回内容", self.driver.find_element(By.CSS_SELECTOR, ".topic-title").text.lower())
        assert "selenium" in self.driver.find_element(By.CSS_SELECTOR, ".topic-title").text.lower()
