# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestSearch1():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_search1(self):
        # Test name: search1
        # Step # | name | target | value | comment
        # 1 | open | / |  |
        self.driver.get("https://ceshiren.com/")
        # 2 | setWindowSize | 1057x814 |  |
        self.driver.set_window_size(1057, 814)
        # 3 | click | css=.d-icon-search |  |
        self.driver.find_element(By.CSS_SELECTOR, ".d-icon-search").click()
        # 4 | click | css=.d-icon-sliders-h |  |
        self.driver.find_element(By.CSS_SELECTOR, ".d-icon-sliders-h").click()
        # 5 | click | id=ember79 |  |
        self.driver.find_element(By.CSS_SELECTOR, ".search-query").click()
        # 6 | type | id=ember79 | selenium |
        self.driver.find_element(By.CSS_SELECTOR, ".search-query").send_keys("selenium")
        # 7 | click | css=.btn-primary |  |
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        # 8 | click | css=#ember106 > .search-highlight:nth-child(2) |  |
        self.driver.find_element(By.CSS_SELECTOR, ".modal-close").click()
        # 9 | runScript | window.scrollTo(0,100) |  |
        self.driver.execute_script("window.scrollTo(0,100)")
        # todo:10.显示等待

        print("=====")

    def test_date(self):
        self.driver.get("C:/Users/guohongliang/Desktop/ceshi.html")
        print("")
        i = self.driver.find_element(By.XPATH, "//input[@type='date']")
        i.clear()
        i.send_keys("2023/12/12")
        print("")
